name: bistring
channels:
  - defaults
dependencies:
  - nodejs
  - pip
  - pip:
    - sphinx
    - sphinx_autodoc_typehints
    - sphinx_rtd_theme
    # Need fixes for https://github.com/mozilla/sphinx-js/issues/90,
    # https://github.com/mozilla/sphinx-js/issues/105,
    # https://github.com/mozilla/sphinx-js/issues/110
    - "git+https://github.com/tavianator/sphinx-js@d2e98fb07c8d2efe46820f1ab07a677244dc4dce#egg=sphinx-js"
    - regex
